#! /bin/sh
# /etc/init.d/tomcat8

### BEGIN INIT INFO
# Provides: tomcat8
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Tomcat8 at boot time
# Description: Enable service provided by daemon
### END INIT INFO

# Developed by: Vinicius Celms
# Date: 2016/04/22
# Description: Control Tomcat8 Server

JAVA_HOME=JDK_SYSTEM_DIRECTORY
export JAVA_HOME

TOMCAT=TOMCAT_SYSTEM_DIRECTORY

case "$1" in
    start)
        echo "Starting Tomcat"
        $TOMCAT/bin/startup.sh
        ;;
    stop)
        echo "Stopping Tomcat"
        $TOMCAT/bin/shutdown.sh
        ;;
    restart)
        echo "Restarting Tomcat"
        $TOMCAT/bin/shutdown.sh
        $TOMCAT/bin/startup.sh
        ;;
    *)
        echo "Usage: /etc/init.d/$(echo $TOMCAT | cut -d/ -f3 | cut -d_ -f1) {start|restart|stop}"
        exit 1
        ;;
esac

exit 0
